### ISSUE TITLE
Connecting to the lenses?

### ISSUE THREAD

**Issue by mcdzim** [howiemnet/h-moco-LENS-Arduino#1]
Hi Howiemnet, 

I am working with the new raspberry pi HQ camera and a few canon lenses having made a 3D printed adapter. How did you manage to connect wires from the arduino to the lenses? 

I know you said you wouldn't fix bugs or documentation but if you feel like taking a picture that would be great :D

**Comment by howiemnet** [comment]
Both by using a macro extender (which passes through the connections - you can tap into them) or just taking the lens apart: http://howiem.com/wordpress/index.php/2016/07/07/motion-control-canon-ef-lens-hacking/ :)

**Comment by mcdzim** [comment]
Amazing thanks
